### ISSUE TITLE
Split Episode 07 Using Transformations into more granular lessons

### ISSUE THREAD

**Issue by ostephens** [data-lessons/library-openrefine#15]
Suggest:
1. Introduction to Transformations
2. Writing Transformations
3. Undo and Redo
4. Exporting data
5. Introduction to data types
6. Working with Arrays

**Comment by ccronje** [comment]
Restructuring suggestion from meeting http://pad.software-carpentry.org/post-lc2017 (OpenRefine Discussion Agenda):

1. Built-in transformations
2. Writing transformations
3. Undo-redo, extract-apply, export
4. Data types
5. Arrays

Also discussed:
- Re-working the array section, maybe use alternative example to the 'days of the week' e.g. demo array examples in GREL preview window using Subject column data.
- Removing the use of 'match' in this episode, because split will suffice. This also avoids engaging with regular expressions at this point.

**Comment by drjwbaker** [comment]
Further to chat with @ostephens on Gitter, the current position of the export bit in this episode feels awkward. The Refine instructor at the event I helped at this week moved it to the end of the episode because they thought that made for a better conclusion (they didn't get to the following episode, so export became the end of the lesson). Do with that observation what you will!

**Comment by ccronje** [comment]
Thanks for the feedback @drjwbaker - @ostephens I do like the idea of finishing up the lesson with exporting data. Perhaps the lesson could finish on the CrossRef API advanced exercise, followed by Extract/Apply and Export? Undo/Redo seems to sit well with the GREL as people get a bit anxious at this point about making mistakes.

**Comment by ostephens** [comment]
I think when we split out this episode into smaller parts we should look at expanding the Export section (to cover different types of export). We can then decide where it should go in the default order - from a lesson flow perspective I think putting it at the end makes sense - I just wouldn't want it to be skipped in the case where your weren't able to cover all the material (whereas I think some of the advanced stuff can be skipped and the lesson is still 'complete' in some sense)

**Comment by ccronje** [comment]
That sounds like a sensible way forward @ostephens

**Comment by pitviper6** [comment]
I'm splitting this lesson up (and watching bobsledding).

What about putting the Export into it's own short lesson, so that no matter where the OR lesson ends, the instructor can grab it and end with it? Where you end with OR can depend on the people in the room, so going in you may not end up where you think you're going to. Keeping it free-floating makes it easier to plug in wherever.

**Comment by ostephens** [comment]
@pitviper6 yes please! I'd like to expand the Export section eventually (see my comment above), so getting what we have in it's own section would be a great first step

**Comment by pitviper6** [comment]
@ostephens @ccronje 
When you two have time, could you take a look and see if what I did make sense to you? No hurry! but if you two agree this looks good we can go ahead and merge.

**Comment by ccronje** [comment]
Thanks @pitviper6 :1st_place_medal:
